### ISSUE TITLE
Support java 8 syntax, such as lambda expressions 

### ISSUE THREAD

**Issue by dbaxa** [c2nes/javalang#17]
Currently javalang raises an error when it encounters the new lambda expression syntax that java 8 provides and instead (of raising an error) it should parse the code.

Here is an some java that triggers an error in javalang (taken from http://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html)

	public class Calculator {
	  
	    interface IntegerMath {
		int operation(int a, int b);   
	    }
	  
	    public int operateBinary(int a, int b, IntegerMath op) {
		return op.operation(a, b);
	    }
	 
	    public static void main(String... args) {
	    
		Calculator myApp = new Calculator();
		IntegerMath addition = (a, b) -> a + b;
		IntegerMath subtraction = (a, b) -> a - b;
		System.out.println("40 + 2 = " +
		    myApp.operateBinary(40, 2, addition));
		System.out.println("20 - 10 = " +
		    myApp.operateBinary(20, 10, subtraction));    
	    }
	}

**Comment by c2nes** [comment]
Hi dbaxa, sorry for the delay in responding. I would like to have Java 8 support added, but I won't have time to work on this myself for a while. I would be happy to accept a pull request if you or anyone else was interested in making the changes.

**Comment by dbaxa** [comment]
Okay.

**Comment by dbaxa** [comment]
See #18 .

**Comment by dbaxa** [comment]
I am going to close this issue.
