### ISSUE TITLE
Node __equals__ not reflexive

### ISSUE THREAD

**Issue by sdjespersen** [c2nes/javalang#19]
I'm a bit confused by [these two lines](https://github.com/c2nes/javalang/blob/master/javalang/ast.py#L35-L36). Shouldn't this instead read
```python
if type(other) is not type(self):
    return False
```
with a `not` in there? Consider the following:
```python
tree = javalang.parse.parse('')
tree.__equals__(tree) # returns False
```

**Comment by dbaxa** [comment]
@sdjespersen that certainly seems the case to me.

**Comment by c2nes** [comment]
@sdjespersen Thanks for the heads up! Just pushed a fix. Let me know if you find any other problems and feel free to open a pull request (or issue) if you have ideas for anything that could be added/improved.
