### ISSUE TITLE
unary operators parsed but no has no corresponding entity or parameters in javalang

### ISSUE THREAD

**Issue by sandeshc** [c2nes/javalang#26]
On parsing the following test case with __javalang__ it wasn't able to detect the unary (prefix) operator `++`.
The issue is prevalent for other unary operators as well, such as `+, -, ++ (postfix), !`

```
class Test
{
    Test()
    {
        x = ++y;
    }
}
```

Output on parsing above test file : [issue_output](http://pastebin.com/raw/T8Ae2JU4)
The operator has no entry in the output ( test file is being parsed successfully ).

**Comment by c2nes** [comment]
Thanks @sandeshc. Turned out it was a simple naming mismatch between the parser and AST tree definition. Just pushed up a fix.

**Comment by sandeshc** [comment]
@c2nes Thanks for the quick fix. :)
