### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by kenzierocks** [c2nes/javalang#34]
I'd appreciate it if you could release a new version with the Java 8 support. Thanks for writing this!

**Comment by Gohla** [comment]
Same here. [Javasphinx](https://github.com/bronto/javasphinx/) uses this library to parse Java files to generate sphinx API documentation, but fails to parse Java 8 default methods (bronto/javasphinx#60). Would be great to release this support so it can be used in Javasphinx.

**Comment by c2nes** [comment]
Sorry for the delay!

I've just released and uploaded 0.10.2.
