### ISSUE TITLE
Catching all assignments

### ISSUE THREAD

**Issue by pedromartins4** [c2nes/javalang#40]
Hi. I want to capture all the assignments in a source code file, which I am doing with
`for path, node in tree.filter(javalang.tree.Assignment):`
`  assign +=1`
, but the final result is not the number of assignments I have in the code. A look at the Java specification from the Oracle website doesn't make it clear which Node type should I try to catch for a 'generic' assignment.

Great work with this parser.
Thanks

**Comment by c2nes** [comment]
The code you've given should find assignment _expressions_, but won't find variable (or field) initializers. For those you can try looking for `VariableDeclarator`. If this doesn't explain the discrepancy could your provide a code sample which reproduces the issue?

**Comment by pedromartins4** [comment]
Sorry for the late reply and thanks for your help. I did not immediately realize that variable declarations were a specific tree node and was trying to catch everything through assignments.
