### ISSUE TITLE
Is there a way to print a node to string?

### ISSUE THREAD

**Issue by foresightyj** [c2nes/javalang#45]
Is there a way to convert a node (e.g. `MethodDeclaration`) into a string, either pretty-print (aka, reformatting) or print the original code?

I didn't find such methods in javalang. I had experiences with Roslyn in .net and [javaparse](https://github.com/javaparser/javaparser). Both support this functionality.

**Comment by ConflictGK** [comment]
If I understand correctly you need to retrieve the name of the method being declared. In that case check the attributes:
1) node.name
2) node.children

**Comment by foresightyj** [comment]
No. I meant the entire code of a method in string. For example, javaparser even supports two types: one that pretty prints the code and one that preserves the original spaces.

**Comment by c2nes** [comment]
Unfortunately there is no (easy) way to do this at the moment. There are a couple related issues which would address this if someone was up to attempting them and submitting a PR, #37 and #14

**Comment by foresightyj** [comment]
Thanks for the response :-)

**Comment by leviv** [comment]
This is very old but this is the solution I came up with for my problem.

```python
    def get_code_snippet (lines, index):
            openingBrackets = 0;
            closingBrackets = 0;

            # Resulting snippet
            snippet = ""

            # loop until we find the final closing bracket, or go over the limit
            while index < len(lines):
                line = lines[index]
                for letter in line:
                    if letter == '}':
                        closingBrackets += 1
                    elif letter == '{':
                        openingBrackets += 1

                    snippet += letter

                    # Early end if we have reached last bracket
                    if closingBrackets == openingBrackets and openingBrackets != 0:
                        return snippet
                    
                index += 1

            return snippet
```

I called the method in this way:
```python
lines = code.split("\n")
for child in node.body:
    get_code_snippet (lines, child.position[0] - 1)
```

I hope it can help anyone who stumbles upon this!

**Comment by aminallahrabi** [comment]
how to use your code ? ( what is node ?) @leviv
