### ISSUE TITLE
How do I get a method's parameter's type?

### ISSUE THREAD

**Issue by foresightyj** [c2nes/javalang#46]
This is my code:

    fht_android_src = "E:/FHT Mobile/Android/fht/app/src/main/java/com/fht360/fht"

    for (dirpath, dirname, filenames) in os.walk(fht_android_src):
        for filename in filenames:
            if filename.endswith(".java"):
                filepath = os.path.join(dirpath, filename)
                # see https://stackoverflow.com/questions/19591458/python-reading-from-a-file-and-saving-to-utf-8
                if filename == "MainActivity.java":
                    with io.open(filepath, 'r', encoding="utf8") as f:
                        content = f.read()
                        tree = javalang.parse.parse(content)
                        for path, node in tree:
                            # if isinstance(node, javalang.tree.ClassDeclaration):
                            #     # print(path, node)
                            #     print(node.name)
                            if isinstance(node, javalang.tree.MethodDeclaration):
                                # print(path, node)
                                if node.name == "onEvent":
                                    handlerNode = node
                                    handlerPath = path
                                    print(handlerNode.parameters[0].type, handlerNode.parameters[0].name)

I am analyzing a typical Android Activity class, which have a bunch of `onEvent` methods for EventBus, these methods look like:

    public void onEvent(UnreadChatMessageEvent event) {
        mNavFragment.showHomeDot(event.count);

        SPUtil.saveInteger(this, Constant.UnReadChatMessage, event.count);
        doTotalCount();
    }

    public void onEvent(FriendRequestMsgDotClearEvent event) {
        mNavFragment.showFriendsDot(0);

        SPUtil.saveInteger(this, Constant.UntreatedFriendRequest, 0);
        doTotalCount();
    }

I want to get the type of the notification as something like: `UnreadChatMessageEvent`, but the type given by javalang is always `ReferenceType`:

![image](https://user-images.githubusercontent.com/1296736/29612365-96ff0cd6-8833-11e7-9d48-ad4be08b99d6.png)

**Comment by foresightyj** [comment]
OK. I get around it ugly by adding one line to `parser.py`: 

![image](https://user-images.githubusercontent.com/1296736/29614321-558e8b2e-883c-11e7-9f73-38d9843cd018.png)

The value `token` is there but is not passed into FormalParameter. Is there any reason that it is left out?

![image](https://user-images.githubusercontent.com/1296736/29614304-4aa902d4-883c-11e7-8310-d8bc3925732a.png)

**Comment by c2nes** [comment]
`ReferenceType` is actually a type of AST node declared in `javalang/tree.py`. I believe `handlerNode.parameters[0].type.name` would give you what you're looking for.

```python
import javalang.parse
sig = javalang.parse.parse_member_signature(r'''String foo(List<String> bar, Integer baz)''')
print(sig.parameters[0].type.name) # "List"
print(sig.parameters[1].type.name) # "String"
```

**Comment by foresightyj** [comment]
Oh. I feel stupid after seeing your answer. I jumped to conclusion too quickly. Sorry.
