### ISSUE TITLE
javalang.tree.EnumDeclaration fields and methods properties not working

### ISSUE THREAD

**Issue by tonyroberts** [c2nes/javalang#47]
When parsing an enum with fields and/or methods they get parsed correctly, but the fields and methods properties on the EnumDeclaration return empty lists.

It looks like it's just because the properties inherited from TypeDeclaration assume that body is a list of declarations, but that doesn't work for EnumBody (it ends up walking the tree, which yields tuples of path,node).

**Comment by c2nes** [comment]
Good catch and thanks for the fix!
