### ISSUE TITLE
Problem with chained method call

### ISSUE THREAD

**Issue by avancinirodrigo** [c2nes/javalang#89]
First of all, thank you for this fantastic library.

The problem. I think that there is a problem with the qualifier of chaining method call below:
```java
public class JFreeChart {	
    private transient RenderingHints renderingHints;
    public boolean getAntiAlias() {
        Object val = this.renderingHints.get(RenderingHints.KEY_ANTIALIASING);
        return RenderingHints.VALUE_ANTIALIAS_ON.equals(val); // <-- chaining method
    }
} 
```
```
MethodInvocation(arguments=[MemberReference(member=val, postfix_operators=[], prefix_operators=[], qualifier=, selectors=[])], 
	member=equals, postfix_operators=[], prefix_operators=[], 
	qualifier=RenderingHints.VALUE_ANTIALIAS_ON, selectors=[], 
	type_arguments=None)
```

**Comment by lyriccoder** [comment]
1) What is the problem? Could you please clarify&
2) Seems it 's not a method chaining. We have method invocation `equals`, and qualifier of the method invocation is  `RenderingHints.VALUE_ANTIALIAS_ON`
As I see RenderingHints is type (it's a class), VALUE_ANTIALIAS_ON is constant or enum .
So, we have just an invocation here. Chaining methods is when we have a chain of invocations, but we have only 1 invocation here.

**Comment by avancinirodrigo** [comment]
Hi! I see.
I was confused because usually, a qualifier is only a variable on javalang.
I've already handled that specific case.
Thank you!
